# Generated by Django 2.1.3 on 2018-11-27 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='ExpoComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Comentario',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('file', models.FileField(upload_to='uploads', verbose_name='Archivo')),
            ],
            options={
                'verbose_name': 'Archivo',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('image', models.ImageField(help_text='Imagen: 500x500', upload_to='pictures', verbose_name='Imagen')),
                ('authors', models.ManyToManyField(to='appExpo.Author', verbose_name='Autores')),
            ],
            options={
                'verbose_name': 'Obra',
            },
        ),
        migrations.CreateModel(
            name='WorkComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='appExpo.Work')),
            ],
            options={
                'verbose_name': 'Comentario Obra',
            },
        ),
    ]
